### ISSUE TITLE
Container fails if target unavailable

### ISSUE THREAD

**Issue by mentalsoup** [mattwebbio/orbital-sync#30]
### What happened?

The orbital-sync container fails if it is unable to connect to the secondary or primary container.

### Version

1.1.2

### Log output

```shell
9/14/2022, 11:15:54 PM: ➡️ Signing in to https://pihole1.domain...
9/14/2022, 11:15:55 PM: ✔️ Successfully signed in to https://pihole1.domain!
9/14/2022, 11:15:55 PM: ➡️ Signing in to https://pihole2.domain...
file:///usr/src/app/dist/client.js:28
            throw new LoginError(host, {
                  ^
LoginError: Host: https://pihole2.domain

Status Code:
404
Response Body:
404 page not found
    at Client.create (file:///usr/src/app/dist/client.js:28:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async file:///usr/src/app/dist/index.js:15:25
Node.js v18.9.0
```

**Comment by mattwebbio** [comment]
Yeah, I'm working on some better error handling that I'll roll in with https://github.com/mattwebbio/orbital-sync/issues/26. Thanks for the issue, I'll let you know when this is ready.

**Comment by mentalsoup** [comment]
No problem, in general this is working pretty well so far. Thank you.
